import {Recipe} from "../recipe";

export const mockedRecipes: Recipe[] = [
    {
        id: 1,
        name: "Spaghetti Carbonara",
        description: "Classic Italian pasta dish with eggs, cheese, pancetta, and black pepper.",
        ingredients: ["200g spaghetti", "2 large eggs", "100g grated Pecorino Romano cheese", "150g pancetta", "Black pepper"],
        instructions: "Boil spaghetti. In a separate bowl, whisk eggs, cheese, and pepper. Fry pancetta. Combine cooked spaghetti and pancetta. Add egg mixture. Stir until creamy.",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 2,
        name: "Chicken Stir-Fry",
        description: "Quick and flavorful stir-fry with chicken, vegetables, and soy sauce.",
        ingredients: ["400g chicken breast", "1 bell pepper", "1 broccoli head", "3 cloves garlic", "Soy sauce"],
        instructions: "Slice chicken. Stir-fry in a hot wok. Add chopped veggies and minced garlic. Pour in soy sauce. Stir until cooked.",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 3,
        name: "Margherita Pizza",
        description: "Classic Italian pizza topped with tomatoes, mozzarella, and fresh basil.",
        ingredients: ["Pizza dough", "Tomato sauce", "Fresh mozzarella cheese", "Fresh basil leaves", "Olive oil"],
        instructions: "Roll out pizza dough. Spread tomato sauce. Add cheese and basil. Bake in a hot oven until crust is golden.",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 4,
        name: "Grilled Salmon with Lemon Butter",
        description: "Delicious grilled salmon fillet with a zesty lemon butter sauce.",
        ingredients: ["Salmon fillet", "Lemon", "Butter", "Garlic", "Fresh parsley"],
        instructions: "Season salmon. Grill until cooked. Melt butter in a pan. Add lemon juice, garlic, and parsley. Pour over salmon.",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 5,
        name: "Vegetable Curry",
        description: "A flavorful vegetarian curry with a variety of colorful vegetables.",
        ingredients: ["Mixed vegetables (e.g., carrots, potatoes, peas)", "Coconut milk", "Curry paste", "Rice"],
        instructions: "Cook vegetables in coconut milk and curry paste. Serve over rice.",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 6,
        name: "Caesar Salad",
        description: "Classic Caesar salad with romaine lettuce, croutons, parmesan cheese, and Caesar dressing.",
        ingredients: ["Romaine lettuce", "Croutons", "Parmesan cheese", "Caesar dressing"],
        instructions: "Toss lettuce with croutons, cheese, and dressing. Serve chilled.",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 7,
        name: "Chocolate Chip Cookies",
        description: "Soft and chewy chocolate chip cookies with melty chocolate chips.",
        ingredients: ["Flour", "Butter", "Sugar", "Chocolate chips", "Vanilla extract"],
        instructions: "Mix dough. Fold in chocolate chips. Drop spoonfuls onto baking sheet. Bake until golden.",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 8,
        name: "Vegetable Stir-Fry",
        description: "Healthy stir-fry with a variety of colorful vegetables and tofu.",
        ingredients: ["Tofu", "Broccoli florets", "Carrots", "Bell peppers", "Soy sauce"],
        instructions: "Press tofu and cut into cubes. Stir-fry tofu until golden. Add chopped veggies and soy sauce. Cook until tender.",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 9,
        name: "Caprese Salad",
        description: "Simple salad with tomatoes, fresh mozzarella, basil, and balsamic glaze.",
        ingredients: ["Tomatoes", "Fresh mozzarella cheese", "Fresh basil leaves", "Balsamic glaze"],
        instructions: "Slice tomatoes and cheese. Arrange on a plate with basil leaves. Drizzle with balsamic glaze.",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 10,
        name: "Lemon Garlic Shrimp Pasta",
        description: "Delicious pasta dish with succulent shrimp, garlic, and lemon.",
        ingredients: ["Shrimp", "Pasta", "Garlic", "Lemon", "Butter"],
        instructions: "Cook pasta. Sauté shrimp, garlic, and lemon zest in butter. Toss with cooked pasta.",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 11,
        name: "Mushroom Risotto",
        description: "Creamy risotto cooked with mushrooms and Parmesan cheese.",
        ingredients: ["Arborio rice", "Mushrooms", "Onion", "Chicken or vegetable broth", "Parmesan cheese"],
        instructions: "Sauté mushrooms and onion. Add rice and broth, stirring until creamy. Stir in cheese.",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 12,
        name: "Greek Salad",
        description: "Refreshing salad with cucumbers, tomatoes, olives, feta cheese, and Greek dressing.",
        ingredients: ["Cucumbers", "Tomatoes", "Kalamata olives", "Feta cheese", "Greek dressing"],
        instructions: "Chop vegetables and combine with olives and cheese. Drizzle with Greek dressing.",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
]
