import {Recipe} from "../recipe";

export const mockedRecipes: Recipe[] = [
    {
        id: 1,
        name: "Spaghetti Carbonara",
        description: "Plat de pâtes italien classique avec des œufs, du fromage, de la pancetta et du poivre noir.",
        ingredients: ["200g de spaghettis", "2 gros œufs", "100g de fromage Pecorino Romano râpé", "150g de pancetta", "Poivre noir"],
        instructions: "Faites bouillir les spaghettis. Dans un bol séparé, fouettez les œufs, le fromage et le poivre. Faites frire la pancetta. Combinez les spaghettis cuits et la pancetta. Ajoutez le mélange d'œufs. Remuez jusqu'à ce qu'il soit crémeux.",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 2,
        name: "Chicken Stir-Fry",
        description: "Sauté rapide et savoureux avec du poulet, des légumes et de la sauce soja.",
        ingredients: ["400g de blanc de poulet", "1 poivron", "1 tête de brocoli", "3 gousses d'ail", "Sauce soja"],
        instructions: "Coupez le poulet en tranches. Faites sauter dans un wok chaud. Ajoutez les légumes hachés et l'ail haché. Versez la sauce soja. Remuez jusqu'à ce que ce soit cuit.",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 3,
        name: "Margherita Pizza",
        description: "Pizza italienne classique garnie de tomates, de mozzarella et de basilic frais.",
        ingredients: ["Pâte à pizza", "Sauce tomate", "Fromage mozzarella frais", "Feuilles de basilic frais", "Huile d'olive"],
        instructions: "Étalez la pâte à pizza. Étalez la sauce tomate. Ajoutez le fromage et le basilic. Faites cuire au four chaud jusqu'à ce que la croûte soit dorée.",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 4,
        name: "Grilled Salmon with Lemon Butter",
        description: "Délicieux filet de saumon grillé avec une sauce au beurre citronné pleine de peps.",
        ingredients: ["Filet de saumon", "Citron", "Beurre", "Ail", "Persil frais"],
        instructions: "Assaisonnez le saumon. Faites griller jusqu'à cuisson. Faites fondre le beurre dans une poêle. Ajoutez le jus de citron, l'ail et le persil. Versez sur le saumon.",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 5,
        name: "Vegetable Curry",
        description: "Un curry végétarien savoureux avec une variété de légumes colorés.",
        ingredients: ["Légumes mélangés (par ex. carottes, pommes de terre, petits pois)", "Lait de coco", "Pâte de curry", "Riz"],
        instructions: "Faites cuire les légumes dans le lait de coco et la pâte de curry. Servez sur du riz.",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 6,
        name: "Caesar Salad",
        description: "Salade César classique avec de la laitue romaine, des croûtons, du fromage parmesan et une vinaigrette César.",
        ingredients: ["Laitue romaine", "Croûtons", "Fromage parmesan", "Vinaigrette César"],
        instructions: "Mélangez la laitue avec les croûtons, le fromage et la vinaigrette. Servez frais.",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 7,
        name: "Chocolate Chip Cookies",
        description: "Cookies aux pépites de chocolat moelleux et fondants.",
        ingredients: ["Farine", "Beurre", "Sucre", "Pépites de chocolat", "Extrait de vanille"],
        instructions: "Mélangez la pâte. Incorporez les pépites de chocolat. Déposez des cuillerées sur une plaque de cuisson. Faites cuire jusqu'à ce qu'ils soient dorés.",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 8,
        name: "Vegetable Stir-Fry",
        description: "Sauté sain avec une variété de légumes colorés et du tofu.",
        ingredients: ["Tofu", "Bouquets de brocoli", "Carottes", "Poivrons", "Sauce soja"],
        instructions: "Pressez le tofu et coupez-le en cubes. Faites sauter le tofu jusqu'à ce qu'il soit doré. Ajoutez les légumes hachés et la sauce soja. Faites cuire jusqu'à tendreté.",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 9,
        name: "Caprese Salad",
        description: "Salade simple avec des tomates, de la mozzarella fraîche, du basilic et un glaçage balsamique.",
        ingredients: ["Tomates", "Fromage mozzarella frais", "Feuilles de basilic frais", "Glaçage balsamique"],
        instructions: "Coupez les tomates et le fromage en tranches. Disposez-les sur une assiette avec les feuilles de basilic. Arrosez de glaçage balsamique.",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 10,
        name: "Lemon Garlic Shrimp Pasta",
        description: "Délicieux plat de pâtes avec de succulentes crevettes, de l'ail et du citron.",
        ingredients: ["Crevettes", "Pâtes", "Ail", "Citron", "Beurre"],
        instructions: "Cuisez les pâtes. Faites sauter les crevettes, l'ail et le zeste de citron dans du beurre. Mélangez avec les pâtes cuites.",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 11,
        name: "Mushroom Risotto",
        description: "Risotto crémeux cuit avec des champignons et du fromage Parmesan.",
        ingredients: ["Riz Arborio", "Champignons", "Oignon", "Bouillon de poulet ou de légumes", "Fromage Parmesan"],
        instructions: "Faites sauter les champignons et l'oignon. Ajoutez le riz et le bouillon, en remuant jusqu'à ce qu'il soit crémeux. Incorporez le fromage.",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 12,
        name: "Greek Salad",
        description: "Salade rafraîchissante avec des concombres, des tomates, des olives, du fromage feta et une vinaigrette grecque.",
        ingredients: ["Concombres", "Tomates", "Olives Kalamata", "Fromage feta", "Vinaigrette grecque"],
        instructions: "Coupez les légumes et mélangez-les avec les olives et le fromage. Arrosez de vinaigrette grecque.",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
]
